### ISSUE TITLE
BUG: [app crashes when Twitch app is setup]

### ISSUE THREAD

**Issue by nevets323** [wAIfu-DEV/w-AI-fu_v2#12]
**Describe the bug**
When I have my Twitch clientID and Secret it crashes the app with no clear error/

**To Reproduce**
1. Fill out ClientID and Secret
2. App crashes on next launch
3. Remove the ClientID and Secret from auth.json and it launches fine

Log (redacted)
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/36833569/1354fb91-1b18-4704-a4ea-690a6614280a)

**Comment by wAIfu-DEV** [comment]
Hi, it seems to be an intermittent bug that crashes nodejs with no indication on what the actual issue is.
I've encountered it recently but since it got fixed once I rebooted my system, I assumed it was an issue with my system and not the program itself.

This isn't the good kind of bugs as you can imagine.

The only steps that could be taken on your end would be to try again after having rebooted windows, or having to let go of the Twitch functionnalities, or staying on w-AI-fu 2.0.1 until a fix is released.

I'm 99% sure it's linked to the script for the handling of Twitch events, and since this issue never appeared in version 2.0.1, I'll try to fix it by comparing both the old and newer version.
However, since the bug does not appear every time, and has not appeared for me in a relatively long time, I'm not sure I'll be able to fix it on the first patch.

**Comment by nevets323** [comment]
I've had it persist after a reboot so if I can provide any data to help just let me know.

**Comment by wAIfu-DEV** [comment]
I have made some changes in 2.0.3 to how the relevant code is loaded, could you tell me if it works for you?

**Comment by nevets323** [comment]
No longer crashing with the ID and Secret. Thanks!

**Comment by wAIfu-DEV** [comment]
I'll close this issue now, but due to the nature of the bug I'll be reopening if it looks like it didn't get properly fixed
