### ISSUE TITLE
VT Studio API not working

### ISSUE THREAD

**Issue by Excelsus999** [wAIfu-DEV/w-AI-fu_v2#22]
![asas](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/149912072/300186aa-f29e-42c9-8a1a-a426e73da42a)

This messages just start popping up for no reason, also VT Studio plugins just stopped working at all

**Comment by wAIfu-DEV** [comment]
never had this issue before, I'll do some tests to see what could wause it

**Comment by wAIfu-DEV** [comment]
Managed to replicate the issue, w-AI-fu was not sending a authentification request when it should have, will be fixed in next version. 
Lines in question in `source/vtube_studio/vtube_studio.ts`
![image](https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/132222556/b78bbfdb-c826-4aa6-81fa-002499744eab)
(highlighted are the added lines, it should now show a popup in VTS to accept w-AI-fu as a plugin)

**Comment by wAIfu-DEV** [comment]
I'll try to push the update in the near future, a lot of stuff to test and fix before making it public
